<a href="https://colab.research.google.com/github/LivingDeadCloud/FreeCodeCamp/blob/main/Numpy_execises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# https://github.com/ine-rmotr-curriculum/freecodecamp-intro-to-numpy

In [11]:
import numpy as np
print(np.__version__)

1.19.5


In [12]:
# Create a numpy array of size 10, filled with zeros.
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# Create a numpy array with values ranging from 10 to 49
b = np.arange(10, 50, 1)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
# Create a numpy matrix of 2*2 integers, filled with ones.
c = np.ones([2,2], dtype=np.int)
c

array([[1, 1],
       [1, 1]])

In [ ]:
asdasd