<a href="https://colab.research.google.com/github/LivingDeadCloud/FreeCodeCamp/blob/main/numpy_exercises.ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://github.com/ine-rmotr-curriculum/freecodecamp-intro-to-numpy

In [ ]:
# FILE NAME FOR GITHUB:
# numpy_exercises.ipynb

In [1]:
import numpy as np
print(np.__version__)

1.19.5


Array creation

In [ ]:
# Create a numpy array of size 10, filled with zeros.
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Create a numpy array with values ranging from 10 to 49
b = np.arange(10, 50, 1)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# Create a numpy matrix of 2*2 integers, filled with ones.
c = np.ones([2,2], dtype=np.int)
c

array([[1, 1],
       [1, 1]])

In [ ]:
# Create a numpy matrix of 3*2 float numbers, filled with ones.
d = np.ones([3, 2], dtype=np.float)
d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
e = np.ones_like(b) # np.ones_like: Return an array of ones with the same shape and type as a given array.
e

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.
f = np.zeros_like(d) # zeros_like: Return an array of zeros with the same shape and type as a given array.
f

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# Create a numpy matrix of 4*4 integers, filled with fives.
g = np.ones([4, 4], dtype=np.int)*5
g

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
h = np.ones_like(g)*7
h

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
i = np.eye(3) # np.eye: Return a 2-D array with ones on the diagonal and zeros elsewhere.
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Create a numpy array, filled with 3 random integer values between 1 and 10.
# j = np.ones(3, dtype=np.int)*np.random.randint(10)
j = np.random.randint(10, size=3)
j

array([8, 8, 3])

In [6]:
# Create a 3*3*3 numpy matrix, filled with random float values.
X = np.random.random(size=[3, 3, 3])
# X

np.random.randn(3,3,3) # Solution in exercises

array([[[-0.45738711,  1.48101053,  1.28360513],
        [ 0.44220203,  0.30076349, -0.82611797],
        [ 0.74941303, -0.26841728, -0.39965244]],

       [[-1.96247939, -0.59444246, -0.70103442],
        [-0.53133786, -0.82803992, -0.57820647],
        [ 0.26916352, -0.46922069,  0.07248143]],

       [[-0.42528722,  0.60654518, -0.80801205],
        [-0.98468482,  1.14160265, -1.34978389],
        [-0.93931707, -1.62836132, -0.78876332]]])

In [9]:
# Given the X python list convert it to an Y numpy array
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [16]:
#  Given the X numpy array, make a copy and store it on Y.
X = np.array([1, 2, 3])
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # The id is different

[1 2 3] 139949095664576
[1 2 3] 139949094772368


In [19]:
# Create a numpy array with numbers from 1 to 10
x = np.arange(1, 11)
print(x, type(x))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [21]:
# Create a numpy array with the odd numbers between 1 to 10
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [24]:
# Create a numpy array with numbers from 1 to 10, in descending order.
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [29]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
X = np.arange(9)
X = X.reshape([3, 3])
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
# Show the memory size of the given Z numpy matrix
Z = np.arange(9).reshape(3, 3)
Z.nbytes

print("%d bytes" % (Z.size * Z.itemsize))  # Solution in exercises

72 bytes


Array indentation

In [43]:
# Given the X numpy array, show it's first element
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[0]

'A'

In [44]:
# Given the X numpy array, show it's last element
X[-1]

'E'

In [45]:
# Given the X numpy array, show it's first three elements
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

In [46]:
#  Given the X numpy array, show all middle elements
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [47]:
# Given the X numpy array, show the elements in reverse position
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [48]:
# Given the X numpy array, show the elements in an odd position
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [65]:
# Given the X numpy matrix, show the first row elements
X = np.arange(12).reshape(4, 3)
print(X)
X[0,:]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([0, 1, 2])

In [60]:
# Given the X numpy matrix, show the last row elements
X[-1]

array([6, 7, 8])

In [61]:
# Given the X numpy matrix, show the first element on first row
X[0,0]

0

In [62]:
# Given the X numpy matrix, show the last element on last row
X[-1,-1]

8

In [66]:
# Given the X numpy matrix, show the middle row elements
X[1:-1]

array([[3, 4, 5],
       [6, 7, 8]])

In [68]:
# Given the X numpy matrix, show the first two elements on the first two rows
X[:2,:2]

array([[0, 1],
       [3, 4]])

In [81]:
# Given the X numpy matrix, show the last two elements on the last two rows
X[-2:,-2:]

array([[ 7,  8],
       [10, 11]])

Array manipulation

In [85]:
# Convert the given integer numpy array to float
X = [-5, -3, 0, 10, 40]
X = np.array(X, dtype=float)
print(X, type(X))

[-5. -3.  0. 10. 40.] <class 'numpy.ndarray'>


In [89]:
# Reverse the given numpy array (first element becomes last)
X[::-1]

[40, 10, 0, -3, -5]

In [91]:
# Order (sort) the given numpy array
X.sort()
X

[-5, -3, 0, 10, 40]

In [92]:
# Given the X numpy array, set the fifth element equal to 1
X[4] = 1
X

[-5, -3, 0, 10, 1]

In [93]:
#  Given the X numpy array, change the 50 with a 40
X = np.array([10, 20, 30, 50])
X[X==50] = 40
X

array([10, 20, 30, 40])

In [94]:
# Given the X numpy matrix, change the last row with all 1
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1,:] = np.ones(X.shape[1]) # This way the number of elements is determined programmatically
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [99]:
# Given the X numpy matrix, change the last item on the last row with a 0
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1,-1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [100]:
# Given the X numpy matrix, add 5 to every element
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X+5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

Boolean arrays (also called masks)

In [103]:
# Given the X numpy array, make a mask showing negative elements
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X<0
mask

array([ True, False, False,  True, False, False, False, False,  True,
       False])

In [104]:
# Given the X numpy array, get the negative elements
X[X<0]

array([-1, -4, -9])

In [105]:
# Given the X numpy array, get numbers higher than 5
X[X>5]

array([ 6, 10])

In [107]:
# Given the X numpy array, get numbers higher than the elements mean
X[X>X.mean()]

array([ 2,  5,  6, 10])

In [109]:
# Given the X numpy array, get numbers equal to 2 or 10
X[(X==2) | (X==10)]

array([ 2, 10])

Logic functions

In [110]:
# Given the X numpy array, return True if none of its elements is zero
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

In [112]:
# Given the X numpy array, return True if any of its elements is zero
X.any()

True

Summay statistics

In [113]:
# Given the X numpy array, show the sum of its elements
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

X.sum()

43

In [114]:
# Given the X numpy array, show the mean value of its elements
X.mean()

4.777777777777778

In [119]:
# Given the X numpy matrix, show the sum of its columns
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

In [120]:
# Given the X numpy matrix, show the mean value of its rows
X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [121]:
# Given the X numpy array, show the max value of its elements
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

X.max()

10