<a href="https://colab.research.google.com/github/LivingDeadCloud/FreeCodeCamp/blob/main/numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
# https://github.com/ine-rmotr-curriculum/freecodecamp-intro-to-numpy

In [42]:
# FILE NAME FOR GITHUB:
# numpy_exercises.ipynb

In [11]:
import numpy as np
print(np.__version__)

1.19.5


In [12]:
# Create a numpy array of size 10, filled with zeros.
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
# Create a numpy array with values ranging from 10 to 49
b = np.arange(10, 50, 1)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
# Create a numpy matrix of 2*2 integers, filled with ones.
c = np.ones([2,2], dtype=np.int)
c

array([[1, 1],
       [1, 1]])

In [22]:
# Create a numpy matrix of 3*2 float numbers, filled with ones.
d = np.ones([3, 2], dtype=np.float)
d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
e = np.ones_like(b) # np.ones_like: Return an array of ones with the same shape and type as a given array.
e

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.
f = np.zeros_like(d) # zeros_like: Return an array of zeros with the same shape and type as a given array.
f

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
# Create a numpy matrix of 4*4 integers, filled with fives.
g = np.ones([4, 4], dtype=np.int)*5
g

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [33]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
h = np.ones_like(g)*7
h

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [35]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
i = np.eye(3) # np.eye: Return a 2-D array with ones on the diagonal and zeros elsewhere.
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# Create a numpy array, filled with 3 random integer values between 1 and 10.
# j = np.ones(3, dtype=np.int)*np.random.randint(10)
j = np.random.randint(10, size=3)
j

array([8, 8, 3])